### ISSUE TITLE
The hotkey.start()  function is invalid

### ISSUE THREAD

**Issue by okrightall** [spyoungtech/ahk#106]

**Comment by spyoungtech** [comment]
Hi there, can you provide some more information on this?

**Comment by okrightall** [comment]
Thanks a lot.

But the "win+n" hotkey doesn't start Notepad

**Comment by spyoungtech** [comment]
Can you share the code you're using? Also keep in mind that, if your Python script exits, the hotkey will no longer be active.

**Comment by okrightall** [comment]
"if the Python script exits, the hotkey will no longer be active."


Although I don't understand it, I'll try it. The best example is jif, which is placed on jithub, because hotkeys are the most important. I have successfully tested other mouse and keyboard tests. Only the hotkey test failed.

**Comment by spyoungtech** [comment]
The key is to prevent your script from completing.

For example:
```python
hotkey.start()
while True:
    time.sleep(1)
```
