### ISSUE TITLE
Feature/GUI

### ISSUE THREAD

**Issue by spyoungtech** [spyoungtech/ahk#11]
Implement GUI interface. REF: https://www.autohotkey.com/docs/commands/Gui.htm

- [x] FileSelectFile
- [x] FileSelectFolder
- [ ] ~~Gui~~
- [ ] ~~Gui control types~~
- [ ]~~GuiControl~~
- [ ] ~~GuiControlGet~~
- [ ] ~~Gui ListView control~~
- [ ] ~~Gui TreeView control~~
- [ ] ~~IfMsgBox~~
- [ ] ~~Image Handles~~
- [x] InputBox
- [ ] ~~LoadPicture~~
- [ ] ~~Menu~~
- [ ] ~~MenuGetHandle~~
- [ ] ~~MenuGetName~~
- [x] MsgBox
- [ ] ~~OnMessage~~
- [ ] ~~Progress~~
- [ ] ~~SplashImage~~
- [ ] ~~SplashTextOn/SplashTextOff~~
- [ ] ~~Standard Windows Fonts~~
- [ ] ~~Styles for a window/control~~
- [x] ToolTip

**Comment by yedhrab** [comment]
#92
