### ISSUE TITLE
How do You right click?

### ISSUE THREAD

**Issue by Wolvesman** [spyoungtech/ahk#112]
I Have tried various combinations including:
ahk.key_down('shift')
time.sleep(1)
ahk.key_down('{F10}')
time.sleep(1)
ahk.key_up('{F10}')
time.sleep(1)
ahk.key_up('shift') 

The shift key is actvating on the OSK app on windows 10 but not F10.

Thanks for your help.

**Comment by spyoungtech** [comment]
I see. Yeah, I don't think `key_up` and `key_down` work with `{F10}` like that because of how these work... The resulting script would be 
```ahk
SendInput {{F5} up}
```
Which would not be correct.

I think you want to do is `ahk.key_down('F10')`

The resulting script looks like this:

```
SendInput {F5 up}
```
and works as expected

> How do You right click?

```python
ahk.right_click()
```

**Comment by spyoungtech** [comment]
@Wolvesman let me know if you still need help with this. Otherwise, I'll consider the issue resolved.
