### ISSUE TITLE
Incorrect window.rect for some applications i.e. padding that should not be there

### ISSUE THREAD

**Issue by maszaa** [spyoungtech/ahk#113]
For some application windows `Window.rect` returns padding that shouldn't be there.

I demonstrated this with pyautogui for Microsoft Store application HEOS Remote:

```python
from ahk import AHK
import pyautogui

window = AHK().find_window(title=b"HEOS Remote")
window.activate()
screenshot = pyautogui.screenshot(region=window.rect)
screenshot.show()
```

The result is this:
![ahk-window-rect](https://user-images.githubusercontent.com/17689044/105005352-df40c180-5a3d-11eb-95b0-7acfafd94355.png)

This causes mouse clicks close to boundaries to not be inside the window boundaries.

**Comment by maszaa** [comment]
Seems to be related to this: https://www.autohotkey.com/boards/viewtopic.php?t=9093

Maybe the `templates/window/win_position.ahk` script needs some fine tuning? I already tried
```
CoordMode, Pixel, Client
CoordMode, Mouse, Client
```
with no luck.

I have Windows 10 Pro 1909 with scaling set to 300% (I'm using my 4K TV as my screen).

**Comment by spyoungtech** [comment]
Thanks for bringing this up.

Does this issue also occur when your scaling is not 300%?

This may also be related: https://www.autohotkey.com/boards/viewtopic.php?t=9620&p=53376

**Comment by maszaa** [comment]
It also occurs when the scaling is only 100%:
![image](https://user-images.githubusercontent.com/17689044/107400086-29333980-6b0a-11eb-91b8-79a4ee83126c.png)

Anything that can be done in this project to mitigate this issue?

**Comment by spyoungtech** [comment]
Hmm. I'm not sure how I can reproduce this issue, so I'm not sure how to test possible fixes. I would try taking a look at window spy and see if there's anything interesting about the border area.

Maybe the Client size will work better?


https://autohotkey.com/board/topic/91733-command-to-get-gui-client-areas-sizes/


AHK v2 has this feature builtin and so would be supported in the future.

https://lexikos.github.io/v2/docs/commands/WinGetClientPos.htm
