### ISSUE TITLE
Breaking a running script

### ISSUE THREAD

**Issue by mrsweck** [spyoungtech/ahk#118]
To my colleagues I have made a script for updating our old documents to a new document standard. It takes the content from old document and put it into its own (empty) template which is then saved to a new file. This is done in a loop and updates all files in a chosen folder. Things CAN get incorrect depending on both the content of the old document and the fact that it's made in an older Office version. Therefore I would like a possibility to stop a running operation and for their convenience **without** exiting everything (closing the GUI with it).

**Comment by spyoungtech** [comment]
There may be a few ways to do this, but would depend quite a bit on how you have implemented your program/GUI. For example, is your GUI script also responsible for processing the folder? Are you using blocking or nonblocking interfaces?

It sounds like you may be performing quite a bit of work in AHK. If you are able to share the code, I may be able to help you figure something out.

But in any case, some initial thoughts around this that may help:

If not already, you might want to consider separating the GUI process from the AHK process(es) that perform the document updates. That way, you would be able to independently stop the processing from the GUI.

When using nonblocking interfaces, you are able to use the `kill` method to stop the AHK process:

```python
proc = ahk.run_script(blocking=False)
...
if condition:
    proc.kill()
```

It is possible to communicate between Python and an actively running AHK script. One example was previously discussed [here](https://github.com/spyoungtech/ahk/issues/43). Here, AHK writes to a file monitored by Python. The inverse could also be done -- or even other mechanisms, like queues, databases, or whatever.

Hope that helps.

**Comment by spyoungtech** [comment]
Closing this for now, if you still need help @mrsweck let me know
