### ISSUE TITLE
How to run the same action chain multiple times

### ISSUE THREAD

**Issue by pistacium** [spyoungtech/ahk#120]
Currently I'm making a program to hotkey to reset a world in a game, with specific settings that the user chooses through a tkinter GUI. I make an action chain so that I can set up a global hotkey outside of the GUI class and run the ActionChain (which was defined in the GUI class) outside the GUI class. However, after running the action chain once, I can't run the same chain again. Is this even something possible to be able to do?

**Comment by lilgandhi1199** [comment]
Upload your code

**Comment by spyoungtech** [comment]
Currently, this is not possible. However, it should be possible to change the implementation to allow this. I'll add this change in the near future.

**Comment by spyoungtech** [comment]
Action Chains will be removed in v1, hence closing this issue.
