### ISSUE TITLE
is there full Hotkey and Hotstring support?

### ISSUE THREAD

**Issue by levavft** [spyoungtech/ahk#121]
Hi, I was wondering If there was support for everything that has to do with hotkeys and hotstrings?
for example, support for hotstring options (:?o:somestring::someotherstring)

**Comment by spyoungtech** [comment]
Almost. Technically, every functionality of AHK is supported through the `.run_script` API. Hotkeys are supported directly in the API (`ahk.hotkey`), but Hotstrings are not _directly_ supported by the API.

I'll make a note to implement hotstrings in the near future.

However, you can implement hotstrings yourself using `run_script` like:

```python
from ahk import AHK
ahk = AHK()
hotstring = ahk.run_script('::btw::by the way', blocking=False)
print('hotstring active! Press ctrl+c to stop'
while True:
    try:
        time.sleep(0.5)
    except KeyboardInterrupt:
        hotstring.terminate()  # stop the hotstring script
        break
```

**Comment by levavft** [comment]
thank you very much! and there is no issue with running multiple hotstrings in a single script, or, multiple scripts of a single hotstring right?

**Comment by spyoungtech** [comment]
There's no particular issue with this, no. Though something to be aware of: every time you call `run_script` you're creating a new process. So, in general, it would be better to shove them all into a single script if you have dozens of them.

**Comment by levavft** [comment]
ty so much!
