### ISSUE TITLE
control click in python ahk?

### ISSUE THREAD

**Issue by intothefantasy** [spyoungtech/ahk#126]
i think i cant find control click in python ahk, so wondering if there is any replacement for this? i wanted to emulate mouse click without moving the cursor which is why i am looking on control click

**Comment by spyoungtech** [comment]
So, this is implemented in the `Window` API in `win.click` where `win` is a `Window` object (as returned by `find_window`, for example). I'm not sure there's anything else to implement here.

The only other thought would be to support clicking controls by something other than their position, but that's covered by #24 

So unless there's something I'm missing, I think I will close this issue and any future work with ControlClick would be tracked as part of #24

But feel free to reopen if I've missed something.
