### ISSUE TITLE
Question: Would you put templates for control functionality in the window dir or a new control dir

### ISSUE THREAD

**Issue by zxrobinson** [spyoungtech/ahk#135]
Right now, I'm working on some of the control functionality. I'll need new templates. Would you prefer that they be in the windows dir or a new peer control directory?

**Comment by spyoungtech** [comment]
Hi @zxrobinson great question and thanks for considering making a contribution.

I have no strong opinion. You could also do both.

In general, use the window dir for anything that's _exclusively_ related to functionality of windows (ie the `Window` class or methods that return an instance of `Window`). In other words, if there's no use of a template outside of windows, then it's a good idea to put it there.

If control functionality can be used outside of the context of a window (say, `ControlClick` with x/y coordinates) , then maybe it's best to be put somewhere else. Maybe a new directory?

Feel free to run with whatever you feel is correct and if I have any strong objections (unlikely) we can always address it in code review in a PR :) 

Hope that helps!
