### ISSUE TITLE
Program started by ahk is exited after python script finishes.

### ISSUE THREAD

**Issue by karolzlot** [spyoungtech/ahk#142]
When another program is started by ahk script inside python, then when python script finishes, this program is exited (in this example slack.exe is exited). (It is exited only if this program was started by ahk inside python, not in case when program was running before)

When I don't use python and only autohotkey .ahk script then this behaviour doesn't happen.

```python
    ahk = AHK()

    ahk_script = r'Run, "C:\Program Files\Slack\slack.exe"'
    ahk.run_script(ahk_script, blocking=False)
```

**Comment by spyoungtech** [comment]
Hmm. I've tried with a few different programs, but I'm not able to reproduce this behavior.

**Comment by karolzlot** [comment]
@spyoungtech Now I think it happens only when I run it from vscode. It seems that vscode kills every spawn process after debugging finishes. So it's not because python or ahk.

Related: https://stackoverflow.com/questions/71439704/how-to-start-another-program-and-keep-it-running-after-python-script-finishes/71441505?noredirect=1#comment126274879_71441505
