### ISSUE TITLE
seconds_to-wait parameter not working on close() method

### ISSUE THREAD

**Issue by jedierik20** [spyoungtech/ahk#144]
I'm closing a (command console) window and when calling thewindow.close() without parameter is seems to be working fine, however, I want to ensure I allow for the running app to shutdown and reset some values.  thewindow.close(seconds_to_wait="6") or any variation of '6', 6, six (that last one for silliness sake) doesn't seem to work - and in fact, seems to PREVENT the close from happening, When using close(seconds_to_wait=anythinghere) - the window no longer closes at all.

**Comment by jedierik20** [comment]
In looking at the source, is it possible it's a positioning problem?  on the run methods as you make the callout - (I'm not a programmer) - it seems like you might need to insert an extra ","   -- so that "Text" parameter is skipped?

**Comment by jedierik20** [comment]
The params for the Autohotkey call are: 
WinClose , WinTitle, WinText, SecondsToWait, ExcludeTitle, ExcludeText  

It looks like you might be doing WinClose, WinTitle, SECONDSTOWAIT
I think it needs to be WinClose, WinTitle, , Secondstowait

**Comment by spyoungtech** [comment]
This should now be fixed in v1
