### ISSUE TITLE
send_input doesn't work with cyrillic text

### ISSUE THREAD

**Issue by rexydye** [spyoungtech/ahk#146]
send_input doesn't work with cyrillic text
![image](https://user-images.githubusercontent.com/42295675/166486513-9cc815ee-49d4-499f-a991-101318eb695f.png)

**Comment by spyoungtech** [comment]
This should be fixed now as part of #132 

Keep in mind that your terminal encoding also plays a role in how text appears. I tested with Notepad and (with #132 merged) it works as expected now.

This change will be available in v0.14.0
