### ISSUE TITLE
Is there a way to send enter key to a program in the background?

### ISSUE THREAD

**Issue by leminhyen2** [spyoungtech/ahk#148]
I'm new to this library and all the examples in the repo seem to only concerns with alphabet keystrokes but not the special keystrokes. I'm very grateful if someone can point me to the right direction

**Comment by spyoungtech** [comment]
You can use the `.send` method of windows for this. This will [use ControlSend](https://github.com/spyoungtech/ahk/blob/c17f80f83c5a09e5fe4c2511ef81339a6e13848b/ahk/templates/window/win_send.ahk#L5) which does not require the window to be focused for the window to receive the input.

Do keep in mind, however, some applications will refuse to accept input unless they are focused (active) and may refuse input if they are minimized -- this is up to the individual application.

I'm not sure exactly what you mean by "special keystrokes", but as of the current version, you can input any keys into this method and it will be sent literally to the generated AHK script (provided you are not using daemon mode). So, you should be able to send any keys accepted by `ControlSend`.


I haven't tested this example, but I think this should answer your question... As an example, assume you have an untitled notepad window open (but not focused).

```python
from ahk import AHK

ahk = AHK()
notepad = ahk.find_window(title=b'Untitled - Notepad')
print(notepad.is_active()) # False if the window is not active/focused
notepad.send('^+a') # send ctrl+shift + a
notepad.send('{Left}') # send left arrow key
notepad.send('{Left}', raw=True) # send the text {Left} literally.
```

**Comment by leminhyen2** [comment]
Woah, thank you so much! so I guess Enter key would be `notepad.send('{Enter}')`?

**Comment by leminhyen2** [comment]
Actually, it's `notepad.send('{Return}')` 

It didn't work for the game I tested but worked on notepad so I guess some programs doesn't accept input while in backgrounds
