### ISSUE TITLE
Get multiple key state?

### ISSUE THREAD

**Issue by newbiemate** [spyoungtech/ahk#164]
I am trying to detect when the user has done a CTRL-C key combination. In AHK, I can do this with:

```
GetKeyState("LCTRL", "c")
```

I see a similar function for this python library do get the same, but the example I see only looks at a single key:

```
ahk.key_state('Control')  # Return True or False based on whether Control key is pressed down
```

How can I accomplish detecting CTRL-C with this python library?  Is this something supported, or if not, can I request it to be part of the roadmap? Thank you!

**Comment by spyoungtech** [comment]
Interesting. I actually wasn't aware `GetKeyState` has this functionality. I'll look to implement this in the future.

**Comment by spyoungtech** [comment]
Circling back around to this @newbiemate , I'm actually not seeing that this functionality is supported in AHK as you describe. [The docs for GetKeyState](https://www.autohotkey.com/docs/commands/GetKeyState.htm) seem pretty clear that you only get the state of one key. The second parameter is for the `mode` not another key.

**Comment by spyoungtech** [comment]
I think this is a case of mistaken use of the API. Since I haven't gotten clarification, I'm going to close this for now. Feel free to reopen a new issue if needed.
