### ISSUE TITLE
Question/Notice: Closing/Breaking/Stopping the AHK program

### ISSUE THREAD

**Issue by MikevanBree** [spyoungtech/ahk#173]
I've seen in past issues, that you could close AHK scripts either by using ".kill()" or ".terminate()"

However, I can't seem to get either one of them working (I'm using ".run_script()"), or get an equivalent in the smart options thing of VSC.

ahk wrapper version: 0.14.1
Python: 3.10

**Comment by spyoungtech** [comment]
Hi @MikevanBree I'm not 100% sure what you mean by "smart options thing of VSC" -- but if you use the nonblocking interface (using the `blocking=False` keyword argument), you will get back a [`Popen` object](https://docs.python.org/3/library/subprocess.html#popen-objects) that you can call the `.terminate` or `.kill` methods on.

```python
process = ahk.run_script(my_script, blocking=False)
...
process.kill() # or process.terminate()
```

Does that help answer your question? If not, maybe providing code to reproduce the issue you're having or describing the error will help me help you.

**Comment by MikevanBree** [comment]
Hey, sorry for the vague description, with the "smart options" I meant the little autofill menu that also shows all available subfunctions when you press "." behind a class.

further, using `.kill()` or `.terminate()` gave me errors about those functions not exisisting

**Comment by spyoungtech** [comment]
Hi @MikevanBree it's possible there is a bug there. Could you share the relevant code and error message you are seeing?

As a complete side note, it may also be worth mentioning that there is an upcoming major update (1.0) which, among other improvements, will have vastly improved support for type hinting (and thereby also improving IDE Intellisense experience when using this library).

**Comment by MikevanBree** [comment]
the code in question:

`import GUI
from ahk import AHK

ahk = AHK()
ahk_script = """
; ---------------------------- HOTKEYS ---------------------------- ;
...
return
"""
ahk.run_script(ahk_script, blocking=False)

ahk.kill()
`

The Traceback:
`Traceback (most recent call last):
  File "c:\Users\vaMi031204\Documents\Python MACRO TOOL\AutoHotKey.py", line 102, in <module>
    ahk.kill()
AttributeError: 'AHK' object has no attribute 'kill'`

**Comment by spyoungtech** [comment]
The problem you have is that `ahk` doesn't have a `kill` method. But the `Popen` object _returned by ahk.run_script_ does.

```python
process = ahk.run_script(ahk_script, blocking=False)
process.kill() # good
ahk.kill() # bad, not a thing
```

Hope that helps clear things up.

**Comment by MikevanBree** [comment]
ahhh okay, is that also the reason it "hangs" my terminal by any chance?

**Comment by MikevanBree** [comment]
note on the previous comment, don't mind that, that was to do with my own code I added in between
