### ISSUE TITLE
Window Crashes When Giving Always On Top Attribute To Itself

### ISSUE THREAD

**Issue by Nulmor** [spyoungtech/ahk#177]
When I give a pygame window always on top attribute it freezes and crashes a few seconds later.
I have tried to give the game window always on top attribute with some other normal AHK file and another python instance, both works fine, but when I try to do it in the same instance it freezes first and after a while it crashes.

Example python code: pressing 1 on the keyboard closes the window, 2 gives always on top(which freezes and then crashes), 3 checks windows with always on top
```python
import pygame
from ahk import AHK

# Set the pygame window
pygame.init()
screen = pygame.display.set_mode((800, 600))
pygame.display.set_caption('Crash Test 1')
screen.fill((0, 255, 255))
pygame.display.update()

ahk = AHK()

isRunning = True
while isRunning:
    for event in pygame.event.get():
        # when 1 on keyboard pressed closes the window
        if ((event.type == pygame.KEYDOWN and event.key == pygame.K_1)
                or event.type == pygame.QUIT):
                isRunning = False

        # 2 gives always on top attribute to the 'Crash Test 1' (self)
        elif (event.type == pygame.KEYDOWN and event.key == pygame.K_2):
            win = ahk.find_window_by_title(b'Crash Test 1')
            win.always_on_top = True
            print(f'Found Window: {win.title}, process: {win.process}\n\n')

        # 3 return all windows that have always on top attribute true
        elif (event.type == pygame.KEYDOWN and event.key == pygame.K_3):
            for window in ahk.windows():
                if window.always_on_top == True:
                    print(window.title)
                    print(window.process)
        
        # game window runs at ~60fps
        pygame.time.wait(17)
```

On the other hand I can give the first window always on top attribute with another instance of python
4 closes the window, 5 gives the first pygame instance always on top (for some reason this way work fine with no crashes), 6 lists the windows with always on top
```python
import pygame
from ahk import AHK

# Set the pygame window 
pygame.init()
screen = pygame.display.set_mode((800, 600))
pygame.display.set_caption('Crash Test 2')
screen.fill((0, 255, 255))
pygame.display.update()

ahk = AHK()

isRunning = True
while isRunning:
    for event in pygame.event.get():
        # 4 closes this window
        if ((event.type == pygame.KEYDOWN and event.key == pygame.K_4)
                or event.type == pygame.QUIT):
                isRunning = False

        # 5 gives always on top attribute to the other window 'Crash Test 1' (not this window)
        elif (event.type == pygame.KEYDOWN and event.key == pygame.K_5):
            win = ahk.find_window_by_title(b'Crash Test 1')
            win.always_on_top = True
            print(f'Found Window: {win.title}, process: {win.process}\n\n')

        # 6 return all windows that have always on top attribute true
        elif (event.type == pygame.KEYDOWN and event.key == pygame.K_6):
            for window in ahk.windows():
                if window.always_on_top == True:
                    print(window.title)
                    print(window.process)
        
        # game window runs at ~60fps
        pygame.time.wait(17)
```
Also wanted to say thanks for developing this awesome python wrapper 

Currently Installed Versions:
Python 3.10.8
ahk        0.14.1
pygame     2.1.2

EDIT(27.10.2022):
I have tried several other window functions most crash the program when used on self but some do not.
Those that crash are:
```python
win.always_on_top (doesnt crash when just printed as a statement but crashes when set to a bool)
win.hide()
win.maximize()
win.minimize()
win.disable()
win.enable()
win.to_top()
win.to_bottom()
win.move()
```
Those that do not crash:
```python
win.close()
win.activate()
win.activate_bottom()
win.restore()
win.show()
win.send()
```

Also tried to give other GUI elements made from other modules a try, but they also freeze/crash.
For example here I tried with PySimpleGUI it crashes when I make it give itself always on top, maximize or minimize.
```python
import PySimpleGUI as sg
from ahk import AHK

layout = [[sg.Text("Hello from PySimpleGUI")], [sg.Button("OK"), sg.Button("Test")]]
window = sg.Window("simple gui crash test", layout)

while True:
    event, values = window.read()

    # crashes when Test button is clicked
    if event == "Test":
        ahk = AHK()
        win = ahk.find_window_by_title(b'simple gui crash test', exact=True)
        # win.always_on_top = True
        # win.maximize()
        win.minimize()
    
    if event == "OK" or event == sg.WIN_CLOSED:
        break

window.close()
```
Version:
PySimpleGUI 4.60.4

**Comment by spyoungtech** [comment]
I should be able to get around to investigating this myself soon... at first glance, I wonder if the crash is the result of blocking the GUI event loop for too long (the AHK commands can take some time to execute). You could try invoking `ahk` methods from a separate thread and see if that helps.

**Comment by Nulmor** [comment]
Yeah you were right I tried to implement multithreading and it works now, thanks for the pointer!
Also I'm kind of curious as well to how would you have done it? Since this is my first time trying multithreading in Python please do give out any tips if you might have any. Besides that, you can close this thread as you like, thanks again.
```python
import pygame
from ahk import AHK
import _thread


def StartGUI():
    pygame.init()
    screen = pygame.display.set_mode((800, 600))
    pygame.display.set_caption('Crash Test')
    screen.fill((0, 255, 255))
    pygame.display.update()

    isRunning = True
    while isRunning:
        for event in pygame.event.get():
            if ((event.type == pygame.KEYDOWN and event.key == pygame.K_1)
                    or event.type == pygame.QUIT):
                    isRunning = False
            elif (event.type == pygame.KEYDOWN and event.key == pygame.K_2):
                print('foo')
            elif (event.type == pygame.KEYDOWN and event.key == pygame.K_3):
                ahk = AHK()
                win = ahk.find_window_by_title(b'Crash Test', exact=True)
                t1 = _thread.start_new_thread(SetWinOnTop, (win, ))

                print('Done')
            
        pygame.time.wait(17)

def SetWinOnTop(win):
    win.always_on_top = True

if __name__ == "__main__":
    StartGUI()
```

**Comment by spyoungtech** [comment]
Glad that helped. 

> Since this is my first time trying multithreading in Python please do give out any tips if you might have any

As a starting point for learning about threading and concurrency in Python, I would watch [this keynote presentation](https://www.youtube.com/watch?v=9zinZmE3Ogk).

> Also I'm kind of curious as well to how would you have done it?

What you have is probably fine. 

Usually, I would have one or more "worker" threads running that receive work through a queue (a `queue.Queue` object or similar). The main thread (your GUI app) would place work onto the queue(s) (`q.put`) and the worker thread(s) would pull tasks off the queue(s) (`q.get`) in a loop, then eventually mark the task as done (`q.task_done`). In some ways, the implementation would look a lot like your pygame event loop.

Using a queue can give you some additional control over how your app executes work in parallel, as well as provide some additional tools (for example, you can `.join` on a queue to wait for all tasks submitted to the queue be marked done). You can also potentially avoid the creation of many threads, which can otherwise make debugging tasks difficult. 

Though, that may not be 100% necessary in your case and the way I do things may not necessarily be the best, it's just what usually works for me :-)

Hope that helps! Cheers.
