### ISSUE TITLE
Error on import ahk

### ISSUE THREAD

**Issue by Xaelitry** [spyoungtech/ahk#179]
Not sure if this is a version update change on the part of Asyncio or a typo on your part, but I'm running python 3.11 and on import of ahk I get an error from utils.py failing to import coroutine from asyncio, I checked asyncio in my Lib dir and it only contains coroutines.py, there is no coroutine.py, changing the line in utils.py from `from asyncio import coroutine` to `from asyncio import coroutines` fixes the error, but I'm not sure if this causes improper behavior.

**Comment by spyoungtech** [comment]
Fixed in version 0.14.2
