### ISSUE TITLE
Pyinstaller & AutoHotkey.exe

### ISSUE THREAD

**Issue by Poccapx** [spyoungtech/ahk#181]
Currently, when running a script compiled with **Pyinstaller** as single file, either _Autohotkey_ itself or _ahk-binary_ pip package needs to be installed. However, if the same .exe is run on a machine lacking either of these, the `ahk.script.ExecutableNotFoundError` appears, noting that AutoHotkey.exe could not be located.

As [known](http://github.com/spyoungtech/ahk/issues/46), for Pyinstaller the AHK package data has to be added manually, but doing something like `--add-data "C:\Program Files\Python\Lib\site-packages\ahk_binary";ahk_binary` still results in the same error. The size of a compiled .exe (using `--onefile` parameter) does, however, seem to increase by a couple of megabytes – maybe AutoHotkey.exe gets added, but is not found by the AHK part of the script when run.

What is the correct way to include the whole of _ahk-binary_ or at least _AutoHotkey.exe_ (if only that is needed) when compiling with _Pyinstaller_ as single file, so that Autohotkey doesn’t need to be installed on the target machine?

**Comment by Poccapx** [comment]
Managed to get this working by a two-part fix:

1. Stating a second _add-data_ parameter, to include _AutoHotkey.exe_ in the compiled .exe. Example – to put it in the same included folder as the _ahk_ package: `--add-data "C:\Program Files\AutoHotkey\AutoHotkey.exe";ahk`.

2. Declaring _executable_path_ for the _AutoHotkey.exe_ in the script itself, thus overwriting the default location which fails if Autohotkey isn’t installed. Example – `AHK = ahk.AHK(executable_path = os.path.join(getattr(sys, "_MEIPASS", os.path.dirname(os.path.realpath(sys.executable))), "ahk\\AutoHotkey.exe"))`. Here it could be wise to put the above under `if getattr(sys, "frozen", ""):` so that the default path to AutoHotkey.exe only changes if the script runs when compiled.

With the above a Pyinstaller packaged script, containing AHK commands, will work on systems without neither installed Python, nor installed Autohotkey, making it completely autonomous.

**Comment by spyoungtech** [comment]
Nice. Glad you seem to have gotten this sorted out. 

As a side note, I'm curious if you also had the same issue(s) described in #46 or #107 with data files for the jinja templates.

I've been working on a v1 release for `ahk` -- I'm aiming to ensure PyInstaller is well-supported and provide any required guidance like this in our documentation. 

I was thinking of removing data files from the `ahk` package altogether to avoid that common problem, but not sure if that's necessary or if there's a better way.

**Comment by Poccapx** [comment]
Aye. Haven’t used this Jinja in my code, but [a post](http://github.com/spyoungtech/ahk/issues/46#issuecomment-499904089) in # 46 actually got me on the right track to solve the issue. However, its usage of relative path didn’t work no matter what, so i used an absolute path with _MEIPASS, making it universal. And earlier [another post](http://github.com/spyoungtech/ahk/issues/46#issuecomment-721238391) in # 46 helped with the packages; what are they for anyway?

**Comment by spyoungtech** [comment]
As I understand it, using `__file__` is [now supported](https://pyinstaller.org/en/stable/runtime-information.html#using-file) for apps frozen with pyinstaller, which may be cleaner than `_MEIPASS`.

>  what are they for anyway?

The `--add-data` bit is needed because this project relies on non-python data files (AHK script templates). Under normal conditions, users don't have to worry about this because the data files are bundled with the package when you install it with `pip`. However, pyinstaller does not automatically include these files.

I'm thinking about removing the need for that in a future release so pyinstaller integration is less painful.

**Comment by Poccapx** [comment]
And these templates are essential for correct operation? Agree that usage of __file__ looks cleaner, but it is also much less pedagogical: for someone unfamiliar with how Pyinstaller works, a search for `_MEIPASS` immediately (literally the first hit) leads to answers of what that line does in the code (path to unpacked temp folder) – much less so for the general `__file__`. As my issue was solved, you may close this ticket if suitable
