### ISSUE TITLE
How to get python list into ahk and array back from ahk to python?

### ISSUE THREAD

**Issue by Gh0sTG0** [spyoungtech/ahk#188]
Hi.
Is there some way to communicate my list/array's from python to ahk and back?
I tried to turn array/list into string, but when on big numbers it changes to nothing...

Some parts of what I'm on at this moment just to illustrate:
```
print(len(list)) ; list is pre-filled python list
string_array = "\", \"".join(list)
print(len(string_array))
ahk_script = """
base_array := [\"""" + "\", \"".join(list) + """\"]
MsgBox, % base_array.MaxIndex()
for index, value in base_array
            MsgBox, %value%
"""

result = ahk.run_script(ahk_script)
```
When my `len(list)` = 100, and `len(string_array)` shows me ~8500, I have `msgbox` with `len(list)` number and it starts looping all values.
But when I'm on 1000, and `len(string_array)` shows me ~75000 it `print` me 1000, 75000 and then nothing more happens, no `msgbox`es, etc.
Looks like It somehow overfill... something?

**Comment by spyoungtech** [comment]
This likely has to do with the contents of your list making the resulting code malformed.

You can see this simple example works:

```python
from ahk import AHK
ahk = AHK()

mylist = ['bacon', 'eggs', 'spam']

script = f"""\
myarray := [{', '.join('"'+item+'"' for item in mylist)}]
for index, value in myarray
    MsgBox, %value%
"""
ahk.run_script(script)
```

However, if the items in my array contain characters like literal quotes (`"`), this will break the script. For example, if you had a list like this:
 
 ```python
mylist = ['foo"', '"bar', 'baz']
```

The resulting script looks like this:

```ahk
myarray := ["foo"", ""bar", "baz"]
for index, value in myarray
    MsgBox, %value%
```

and produces an unexpected result with an array of length 2 instead of an array of length 3.

Ultimately, I believe your issue lies in correctly forming your script.

**Comment by Gh0sTG0** [comment]
> This likely has to do with the contents of your list making the resulting code malformed.
> 
> You can see this simple example works:
> 
> ```python
> from ahk import AHK
> ahk = AHK()
> 
> mylist = ['bacon', 'eggs', 'spam']
> 
> script = f"""\
> myarray := [{', '.join('"'+item+'"' for item in mylist)}]
> for index, value in myarray
>     MsgBox, %value%
> """
> ahk.run_script(script)
> ```
> 
> However, if the items in your list contain characters like literal quotes, newlines, escape sequences, etc. this will break the script. For example, if you had a list like this:
> 
> ```python
> mylist = ['foo"', '"bar', 'baz']
> ```
> 
> The resulting script looks like this:
> 
> ```ahk
> myarray := ["foo"", ""bar", "baz"]
> for index, value in myarray
>     MsgBox, %value%
> ```
> 
> and produces an unexpected result with an array of length 2 instead of an array of length 3.
> 
> Ultimately, I believe your issue lies in correctly forming your script.

Hi, thanks for your answer.
I tried to `SELECT RANDOM` from sqlite database, and every time I `LIMIT 100` it works... I tried to loop and leave it, it worked for 10+ minutes without any bugs... So it not looks like it's something in one of that lines...
But every time I set it to `LIMIT 1000` it just not works...

**Comment by spyoungtech** [comment]
Ah, I see. That is likely related to a [limitation in AHK itself](https://www.autohotkey.com/boards/viewtopic.php?f=14&p=450587). Each expression can only have so many tokens.
