### ISSUE TITLE
Multiple Scripts Running with window.send() Misses Input

### ISSUE THREAD

**Issue by Suterusu1337** [spyoungtech/ahk#189]
I am trying to run multiple Python scripts concurrently each targeting a different (non-active) window. For the first 1-2 windows, this seams to work, by the 3rd window, some of the .send() keys to the window seem to "get lost", by the 4th window, any keystrokes in semi rapid succession don't seem to work, with a few always missing.

**Comment by spyoungtech** [comment]
I believe this is just an aspect of AutoHotkey itself and a topic that comes up quite often in the ahk forums. You can try adjusting key delay or other techniques.

If you can give an example of AutoHotkey code that works, but has different behavior in the wrapper, or if you can provide some code, maybe I can investigate further.

**Comment by spyoungtech** [comment]
Going to close for inactivity, but feel free to open a new issue if you still have a question.
