### ISSUE TITLE
Add screen capture feature

### ISSUE THREAD

**Issue by Mathiaszero** [spyoungtech/ahk#204]
I would like a method for capturing images on the screen, such as rectangular coordinates, windows, or full shot.  I think it would be very useful.

**Comment by spyoungtech** [comment]
Hmm. I agree this would be useful, but I'm not aware of any functionality in AutoHotkey that does this. So, I'm not 100% sure this functionality belongs directly in `ahk`.

My thought is that your best bet is probably to find a package that provides screen capture capabilities and combine that with the `ahk` package yourself.

From a quick search, [`mss`](https://python-mss.readthedocs.io/examples.html) is a package that provides this functionality. Or you can use something like `PIL` (`pillow`) for working with images -- it also has screen grab functionality, too.

So, with `mss` and `pillow` installed you can perhaps write code like this to make a screenshot from an `ahk` `Window`  object:

```python
from PIL import Image
from mss import mss
from ahk import AHK, Window

def screenshot_window(win: Window) -> Image:
    left, top, width, height = win.get_position()
    capture_area = {'left': left, 'top': top, 'width': width, 'height': height}
    with mss() as sct:
        sct_img = sct.grab(capture_area)
        img = Image.frombytes("RGB", sct_img.size, sct_img.bgra, "raw", "BGRX")
        return img
```

As a working example, you can then use this code something like this, for example to take a screen shot of a Notepad window:

```python
def main():
    ahk = AHK()
    win = ahk.win_get(title='Untitled - Notepad')
    assert win is not None, "You have to open an unedited notepad window first for this sample code to work"
    win.send('hello screenshot')
    win.set_always_on_top('On') # make sure it's visible for the screenshot
    image = screenshot_window(win)
    win.set_always_on_top('Off')
    image.show() # show the image

if __name__ == '__main__':
    main()
```
If you ran this sample code, you should end up being shown a screenshot of a notepad window like this:

![image](https://github.com/spyoungtech/ahk/assets/15212758/d134cb11-d74c-406d-9045-c112b7e70bc1)



Hope that helps.

**Comment by Mathiaszero** [comment]
Thanks for the suggestions and I understand where you are coming from. I agree ahk can be extended in this fashion.
