### ISSUE TITLE
how to remove all hotkey definitions

### ISSUE THREAD

**Issue by nnako** [spyoungtech/ahk#213]
is there a way to remove all or specific hotkey definitions previously created by individual calls of `add_hotkey()`? in Python's `keyboard` package, this can be done by using the function `remove_all_hotkeys()`.

**Comment by spyoungtech** [comment]
Hmm. Right now, there is no such functionality. I will work on adding this functionality in an upcoming release.

As a workaround, you might be able to just replace the hotkey by adding with a no-op function under the same hotkey name. That will overwrite the existing hotkey with a new one that does nothing, although that's not quite the same behavior as removing it.

**Comment by nnako** [comment]
Hi @spyoungtech . Thanks for your reply.

My understanding is that when setting a hotkey, it automatically intercepts the "default" behavior (aha factory settings). Unfortunately, replacing the formerly specifically set hotkey (which was intercepting the original key forwarding) would not be feasible for my usecase. An overwrite with `no-function` would remove the former functionality efficiently. But at the same time continue intercepting the original keys.

I would rather like to **reset** the hotkey to it's "factory" setting in a dynamic way. Each time restoring the factory setting. Thus I would be able to quickly set a specific hotkey when I am in one application scope, and then **reset** all the hotkeys and set some other hotkeys (specific to the new application in scope).

Ok, but I'm looking forward to the upcoming release, hoping that it will fit.

**Comment by spyoungtech** [comment]
Hi @nnako I've submitted a PR to address this issue in #215 

A release candidate `1.2.0rc1` has been published to PyPI. You can install it by running `pip install "ahk==1.2.0rc1"`

As described in the PR, there are four new methods that can be used for removing hotkeys/hotstrings.

Please feel free to take a look, test it out, and provide any feedback. I'll plan to promote the release candidate in the near future.

**Comment by nnako** [comment]
Thanks. the functions `remove_hotkey()` and `clear_hotkeys()` work as expected. the other two I haven't checked.

**Comment by spyoungtech** [comment]
1.2.0 is now released 🎉
