### ISSUE TITLE
How to initiate an external ahk class?

### ISSUE THREAD

**Issue by ssweber** [spyoungtech/ahk#228]
I'd like to use py ahk, but was wondering how to go about initiating an external class

I use https://github.com/Chunjee/graphicsearch.ahk in an application.

It's used like:

```autohotkey
#Include graphicsearch.ahk\export.ahk

oGraphicSearch := new graphicsearch()
result := oGraphicSearch.search("|<HumanReadableTag>*165$22.03z")
```

Do you Is there a way of integrating that into to be used via python?

**Comment by spyoungtech** [comment]
It is possible to extend the library with our own custom functions and code. The interface for this is not yet ready, so it is not documented just yet. There will be an 'official' way to do this in the future that is documented (and will have a very nice interface).

Before I get into extending the library... one possible workaround is to just use `run_script` which can run any arbitrary AHK script you specify (either as a string, or path to a script file).

```python
>>> ahk.run_script('FileAppend, hello world, *, UTF-8')
'hello world'
```
So, maybe you just do something like this:
```python
# ...
script_template = '''\
#Include graphicsearch.ahk\export.ahk

oGraphicSearch := new graphicsearch()
result := oGraphicSearch.search("{}")
FileAppend, %result%, *, UTF-8  ; No idea if this will work... some tweaking may be needed here
'''

def graphic_search(search_arg: str):
    script = script_template.format(search_arg)
    return ahk.run_script(script)
```


-----

But if you want to write an extension in the current version of the library, I'll provide a short tutorial here. It's going to look clunky and you can expect this to change/break in future versions without warning.

First, a little necessary background on how the library itself works:

- Python calls AHK functions by name and can pass any number of strings as parameters.
- Functions written in AHK accept exactly one argument (an array of zero or more strings) and must return responses in a specified message format. There are existing AHK functions for formatting messages that extension authors may use.
- The message indicates the type of the return value so Python can parse the response message into an appropriate Python type. There are several predefined message types defined in the [message module](https://github.com/spyoungtech/ahk/blob/main/ahk/message.py). They are addressed in AHK by the Python class name, but in all uppercase. Users can create their own message types, too -- for example, to have AHK functions return instances of user-defined classes, or whatever, really.


Required elements to implement an extension in the current version:

1. A function written in AHK (v1) that conforms to the required spec (accepts one argument of an array of strings and returns a formatted message). AHK extension scripts are written using [jinja](https://jinja.palletsprojects.com/en/3.1.x/). The user script [extends](https://jinja.palletsprojects.com/en/3.1.x/templates/#child-template) the existing [AHK daemon template](https://github.com/spyoungtech/ahk/blob/main/ahk/templates/daemon.ahk), which includes several predefined blocks that allow extension authors to add additional functions or even alter existing functions.
2. A python method that accepts any required parameters, optionally does input validation/parsing, and ultimately triggers the AHK function call and returns the result.


Here is a complete simple example of adding a function that simply does some basic math. 

<details>
<summary>Simple example</summary>

For simplicity, the AHK portions of the script is simply embedded as a string in the Python script, but they can be written in a separate file and/or simply `#Include`d.

```python
from __future__ import annotations
from typing import Literal
from ahk import AHK

# Define AHK code used in our extended functionality.
# This is a jinja template that extends the default daemon AHK script

EXTENSION_SCRIPT = '''\
{% extends daemon %}

{% block user_directives %}
; you can add directives here

; # Include whatever
{% endblock user_directives %}


{% block before_autoexecute %}
; add additional functions here

SimpleMath(ByRef command) {

    ; All functions MUST return a formatted message of a particular type
    ; There are many builtin message types. These are just two.
    global EXCEPTIONRESPONSEMESSAGE
    global INTEGERRESPONSEMESSAGE
    
    ; `command` is an array with passed arguments, starting at index 2
    lhs := command[2]
    rhs := command[3]
    operator := command[4]
    
    if (operator = "+") {
        result := (lhs + rhs)
    } else if (operator = "*") {
        result := (lhs * rhs)
    } else { ; invalid operator argument
        return FormatResponse(EXCEPTIONRESPONSEMESSAGE, Format("Invalid operator: {}", operator))
    }
    
    return FormatResponse(INTEGERRESPONSEMESSAGE, result)
}
{% endblock before_autoexecute %}
'''

class ExtendedAHK(AHK):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # This is a hack for now... a formal interface will be available in a later version
        self._transport._template = self._transport._jinja_env.from_string(EXTENSION_SCRIPT)


    def simple_math(self, lhs: int, rhs: int, operator: Literal['+', '*']) -> int:
        # validate/transform inputs
        assert isinstance(lhs, int)
        assert isinstance(rhs, int)
        # assert operator in ('+', '*')  # we'll leave this out so we can demo raising exceptions from AHK
        args = [str(lhs), str(rhs), operator]  # all args must be strings
        result = self._transport.function_call('SimpleMath', args, blocking=True)
        return result



if __name__ == '__main__':
    ahk = ExtendedAHK()
    result = ahk.simple_math(2, 4, operator='+')
    print('2 + 4 =', result)
    assert result == 6

    result = ahk.simple_math(2, 4, operator='*')
    print('2 * 4 =', result)
    assert result == 8

    # this will raise our custom exception from our AHK code
    try:
        ahk.simple_math(0, 0, operator='invalid')
    except Exception as e:
        print('That did not work. Error message was:', e)
```

When run, this will produce an output like so:

```
2 + 4 = 6
2 * 4 = 8
That did not work. Error message was: Invalid operator: %
```

</details>

I don't know much about `graphicsearch`, but from a quick look, it seems like the response type from `oGraphicSearch.search` is an array of objects. There currently isn't any message type that handles an array of objects. You would _probably_ have to define a new message type. Or maybe you can use an AHK JSON library to turn the objects into a string and use the string response message type.

This is my attempt at implementing the code snipped you shared, but this is untested:

```python
from __future__ import annotations
from ahk import AHK
from ahk.message import ResponseMessage
import json


# Define AHK code used in our extended functionality.
# This is a jinja template that extends the default daemon AHK script

EXTENSION_SCRIPT = '''\
{% extends daemon %}
{% block user_directives %}
#Include graphicsearch.ahk\export.ahk
#Include Jxon.ahk ; https://github.com/cocobelgica/AutoHotkey-JSON/blob/master/Jxon.ahk
{% endblock user_directives %}


{% block before_autoexecute %}
GraphicSearch(ByRef command) {
    global EXCEPTIONRESPONSEMESSAGE
    global JSONRESPONSEMESSAGE
    
    search_arg := command[2]
    
    oGraphicSearch := new graphicsearch()
    result := oGraphicSearch.search(arg)
    if (result.Length() = 0) {
        return FormatNoValueResponse() ; returns None in Python
    }
    response := Jxon_Dump(result) ; no idea if this works as I expect it to
    return FormatResponse(JSONRESPONSEMESSAGE, response)
}
{% endblock before_autoexecute %}
'''


class JsonResponseMessage(ResponseMessage):
    type = 'json'
    def unpack(self):
        return json.loads(self._raw_content)

class ExtendedAHK(AHK):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # This is a hack for now... a formal interface will be available in a later version
        self._transport._template = self._transport._jinja_env.from_string(EXTENSION_SCRIPT)

    def graphic_search(self, search_arg: str):
        # validate/transform inputs
        args = [search_arg]  # all args must be strings
        res = self._transport.function_call('GraphicSearch', args, blocking=True)
        return res



if __name__ == '__main__':
    ahk = ExtendedAHK()
    result = ahk.graphic_search('|<HumanReadableTag>*165$22.03z')
```

**Comment by ssweber** [comment]
Wow thanks for the detailed response. I’ll give it a shot and report back!

**Comment by ssweber** [comment]
Major thanks! Your ExtendedAHK works perfectly (just small typo, `result := oGraphicSearch.search(search_arg)`)

```python
  result = ahk.graphic_search("|<>*178$14.3w1nknyQTjXzsTy3zUzsTyDrbtvyDz0z2")[0]
  print(result) # {'1': 90, '2': 64, '3': 14, '4': 14, 'id': '', 'x': 97, 'y': 71}

**Comment by ssweber** [comment]
FYI - I ended up using [FindText](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=17834) instead of graphicsearch, since I think 'graphicsearch' was just a fork at one time, while FindText is still updated. But the same extendedahk still works great!

I'm going to work on creating functions for all of FindText functions, and I'll post back some examples so it can be a benefit to other users.

**Comment by spyoungtech** [comment]
Oh, that's interesting!

I've started working on the 'official' interface for extensions. You can check it out in #232 and/or [the docs](https://ahk.readthedocs.io/en/extensions/extending.html) if you're interested to take a look.

I've changed some things up that may break the examples I've shown above -- specifically, how messages work has changed a little bit. Instead of using global variables like `STRINGRESPONSEMESSAGE` or similar, they're now specified using the fully qualified name of the message class, e.g. `FormatResponse("ahk.message.StringResponseMessage", "Hello Extension")`. This will allow authors to provide their own message types with less chance for collisions.

It's also no longer required to subclass `AHK` to provide extensions (again, allowing for easier harmony between multiple extensions). The initial version of the extension interface will just use 'plain' AHK code as text, rather than providing jinja interfaces (I think making a lower barrier to entry).

So, if I were to redo the above example, it'd now look like this, against the `extensions` branch:

```python
from __future__ import annotations
from ahk import AHK
from ahk.extensions import Extension
from ahk_json import JXON # pip install "git+https://github.com/spyoungtech/ahk-json"


EXTENSION_SCRIPT = '''\
GraphicSearch(ByRef command) {
    search_arg := command[2]

    oGraphicSearch := new graphicsearch()
    result := oGraphicSearch.search(search_arg)
    if (result.Length() = 0) {
        return FormatNoValueResponse()
    }
    response := Jxon_Dump(result) ; The JXON extension from ahk_json provides this!
    ; ahk_json also provides the response message used here
    return FormatResponse("ahk_json.message.JsonResponseMessage", response)
}
'''

graphic_search_extension = Extension(script_text=EXTENSION_SCRIPT)

@graphic_search_extension.register
def graphic_search(ahk: AHK, search_arg: str):
    # validate/transform inputs
    args = [search_arg]  # all args must be strings
    res = ahk.function_call('GraphicSearch', args, blocking=True)
    return res


if __name__ == '__main__':
    ahk = AHK(extensions='auto')  # infers extensions=[JXON, graphic_search_Extension]
    result = ahk.graphic_search('|<HumanReadableTag>*165$22.03z')
```

The idea is that one could publish extension modules to PyPI and make it easy to share solutions :-)

**Comment by xfeyz** [comment]
@ssweber have you managed to use the FindText v2 in python? If yes, can you post some examples? Thanks!

**Comment by ssweber** [comment]
@xfeyz if you mean the ahk v2 compatible version, I havn't. @spyoungtech turned me on to jxon_dump, and I ultimately used a simpler ahk wrapper that includes the FindText v1 - see https://github.com/CodeOptimist/ahkunwrapped/issues/2#issuecomment-1690378880
