### ISSUE TITLE
AHK Window "to_top()" freezing Python

### ISSUE THREAD

**Issue by ArieTheTrainGirl** [spyoungtech/ahk#237]
Hi there.
Trying to force a window on top of all others. I'm able to activate the window to put it in focus, but I'd like it to remain on top of all windows.

For some reason whenever I call restore(), to_top(), or set_always_on_top('On'), Python freezes. Any reason why this would be happening?

![image](https://github.com/spyoungtech/ahk/assets/76417791/544b584b-6f85-445c-9d7a-6b20354811c5)

I've tried it with just to_top or set_always_on_top but regardless, it always freezes and when I forcefully close Python processes it throws me this exception:

  File "C:\Users\ariet\AppData\Roaming\Python\Python310\site-packages\ahk\_sync\window.py", line 419, in to_top
    return self._engine.win_set_top(
  File "C:\Users\ariet\AppData\Roaming\Python\Python310\site-packages\ahk\_sync\engine.py", line 2186, in win_set_top
    resp = self._transport.function_call('AHKWinSetTop', args, blocking=blocking)
    return self.send(request, engine=engine)
  File "C:\Users\ariet\AppData\Roaming\Python\Python310\site-packages\ahk\_sync\transport.py", line 781, in send
    raise AHKProtocolError(
ahk._sync.transport.AHKProtocolError: Unexpected data received. This is usually the result of an unhandled error in the AHK process.

Thanks in advance.

**Comment by spyoungtech** [comment]
Hmm. This is a bit unusual. There is a known issue (with AutoHotkey) where the command behind `.to_top` may sometimes have no effect, however, it should not result in the program freezing.

I'll see if I can find a way to reproduce this problem. Does this happen for you with all windows or just certain programs?

**Comment by ArieTheTrainGirl** [comment]
Hey, thanks for the response.

I did some further testing with other windows and the .set_always_on_top('On') works with them... Given that it worked for other windows I attempted to do the same thing by creating a secondary script that runs the AHK commands instead of running those commands in the same script that ran the window. **It worked.**

For context, I was trying to run those AHK commands on a Pygame window. I thought maybe it was because it was a fullscreen app and AHK didn't know how to handle it, but this appears to be an incompatibility issue with trying to run AHK commands inside of the same script running an instance of Pygame. Don't know why it was freezing... either way, I solved that issue.

On another note, yes, the .to_top() function didn't appear to do anything to any of the windows I tried it on. So although the main issue is not a problem anymore (for me, anyhow), the .to_top() having no effect remains an issue.


Thank you so much for looking into this and apologies for any inconvenience.

**Comment by spyoungtech** [comment]
> For context, I was trying to run those AHK commands on a Pygame window. I

If you're running the pygame app in the same Python interpreter process, that could explain it. The call to `.to_top` is blocking by default and it would prevent the Pygame code from responding to the window event, causing a deadlock.

You can try either (1) separating the AHK-related code from your pygame or (2) providing the `blocking=False` parameter when invoking methods that will interact with your Pygame windows within the same script.

If your pygame app is already running in a different process, it may be something else.

**Comment by spyoungtech** [comment]
As a potential workaround for `.to_top` not working, a [suggested workaround](https://www.autohotkey.com/docs/v1/lib/WinSet.htm#Top) is to set the window to be 'always on top' temporarily instead, which most applications seem to respond to better.

```diff
- win.to_top()
+ win.set_always_on_top('On')
+ win.set_always_on_top('Off')
```
