### ISSUE TITLE
NoTrayIcon not works for simple msgbox.

### ISSUE THREAD

**Issue by Gh0sTG0** [spyoungtech/ahk#242]
For some reasons I still **see tray icon** on null project with this code:
```
# pip install -U ahk - the only one installed thing
from ahk import AHK
from ahk.directives import NoTrayIcon

if __name__ == '__main__':
    ahk = AHK(directives=[NoTrayIcon])
    script_path = r'some_loop.ahk'
    ahk.run_script(script_path)
```
And `.ahk` file:
```
MsgBox, hi
ExitApp
```

I'm doing something wrong?

PS `Python 3.11.5`, `AHK v1.1.37.01 (Unicode 64-bit)`, project in `PyCharm v2023.2.1`, latest ahk package that can be installed via `pip install -U ahk`.

**Comment by spyoungtech** [comment]
The `directives` keyword does not apply to scripts that are invoked using the `.run_script` method. When using `run_script`, you must write the directives into the code yourself.

**Comment by Gh0sTG0** [comment]
> The `directives` keyword does not apply to scripts that are invoked using the `.run_script` method. When using `run_script`, you must write the directives into the code yourself.

Aha. Ok. Thanks for answer.
PS Maybe that should be shown somewhere in description?
