### ISSUE TITLE
How to implement HotIf WinActive 

### ISSUE THREAD

**Issue by chierying** [spyoungtech/ahk#245]
Execute a specific key in a specific window. Just like #HotIf WinActive :
The following buttons will only work in the Idea and PyCharm windows
`#HotIf WinActive("ahk_exe ((idea64\.exe)|(pycharm64\.exe))")`

**Comment by spyoungtech** [comment]
This functionality is not directly implemented. However, as a workaround, you can create an equivalent check inside of your hotkey callback function.

**Comment by xxxxue** [comment]
> This functionality is not directly implemented. However, as a workaround, you can create an equivalent check inside of your hotkey callback function.

I have discovered a GitHub repository that implements' hotif '
https://github.com/thqby/pyahk
