### ISSUE TITLE
find window methods

### ISSUE THREAD

**Issue by spyoungtech** [spyoungtech/ahk#26]
Something analogous to selenium's `find_element_by` methods or `BeautifulSoup`'s `find`/`find_all` methods.

I think the API will also be similar with window Controls.

**Comment by spyoungtech** [comment]
These are now available, but the implementation may be subject to change... currently, one pretty much must use byte strings to match titles. Wonder if there's a better way; wonder how AHK does it. 

Previously, titles were attempted to be decoded first, but some window titles (esp browsers) can contain characters that will break decoding. So, for now seems bytes are safest bet.

**Comment by dequation** [comment]
Comment on window title matching:

Supposing the existence of two windows, named

- 'Untitled - Google Search - Google Chrome'
- 'Untitled - Notepad'

ahk.win_get('Untitled') method will return the Notepad  window-object. Closing the Notepad window, it returns the Google window-object.

Is this behavior inherited from AHK, or is it intended to work like this in the wrapper? If so, it'd be great if a kwarg could be added to specify absolute matching (matching also appears to not be case-sensitive).

**Comment by spyoungtech** [comment]
There is a [kwarg for `exact`](https://github.com/spyoungtech/ahk/blob/master/ahk/window.py#L324-L327) in the current implementation. It's just not yet documented :)

If I'm understanding you correctly, that is what you mean by 'absolute matching'

```
find_windows_by_title(b'Untitled - Notepad', exact=True)
```

**Comment by dequation** [comment]
That is precisely what I mean - 'exact' :-)

Thanks. Really looking forward to that documentation.

**Comment by spyoungtech** [comment]
The underlying implementation may change, but find_window(s) has been more or less complete for a while. 

Closing this as done.
