### ISSUE TITLE
mouse_drag method errors with "Invalid index.. Specifically: 8"

### ISSUE THREAD

**Issue by HeroShiner46** [spyoungtech/ahk#264]
I am trying to use ahk.mouse_drag, but despite what I do it always errors with "Invalid Index.. Specifically: number". This is my code:

ahk.mouse_move(500, 500)
ahk.key_press("RButton")
ahk.mouse_drag(500, 600)
ahk.key_release("RButton")

**Comment by spyoungtech** [comment]
Thanks for the report. I confirmed this is a bug that exists when using AutoHotkey version 2. I will look into it and see if I can get a fix out ASAP.

**Comment by spyoungtech** [comment]
@HeroShiner46 this has been fixed in #265 and has been released in version 1.5.1  -- let me know if this fixes your problem or if you have any other further issues.
