### ISSUE TITLE
This project needs documentation

### ISSUE THREAD

**Issue by spyoungtech** [spyoungtech/ahk#29]
Methods need docstrings. 

Want to also produce some documentation in the form of sphinx + autodoc to be published via readthedocs.

**Comment by Nickiel12** [comment]
What kind of docstring formatting does that require?

**Comment by spyoungtech** [comment]
This project uses [Sphinx docstrings](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html). Eventually, the project will also have full documentation will also be sphinx/rst.

**Comment by spyoungtech** [comment]
Basic documentation is up. Will be a continual work in progress
