### ISSUE TITLE
Tooltip text and title mixed up

### ISSUE THREAD

**Issue by michaelmesser** [spyoungtech/ahk#295]
### describe your issue

Title and text get switched with AHKv2.
I assume this is because the argument order changed between AHK v1 and AHK v2.

![Code_mIZy73O1hQ](https://github.com/spyoungtech/ahk/assets/16529951/5b59dc08-2386-47cd-816c-e2f59f350104)

### ahk.__version__

1.6.3

### AutoHotkey version

v2

### Code to reproduce the issue

```python
ahk.show_traytip(title="Title", text="Text")
```

**Comment by spyoungtech** [comment]
Thank you for the report, I'll have a fix for this available shortly.

**Comment by spyoungtech** [comment]
The fix for this is now released in [version 1.7.1](https://github.com/spyoungtech/ahk/releases/tag/v1.7.1) 🎉
