### ISSUE TITLE
ahk.key_state("XButton2") does not return true in V2

### ISSUE THREAD

**Issue by trajano** [spyoungtech/ahk#297]
### describe your issue

Trying to implement this
```
XButton2::
    {
        While GetKeyState("XButton2", "p") {
            SendEvent "{WheelUp}"
            Sleep 10 
        }
    }
```
But `ahk.key_state("XButton2")` never returns true

### ahk.__version__

4.11.0

### AutoHotkey version

v2

### Code to reproduce the issue

```python
from ahk import AHK

ahk = AHK(executable_path='C:\\Users\\trajano\\AppData\\Local\\Programs\\AutoHotkey\\v2\\AutoHotkey64.exe',
    version='v2')

def scroll_up():
    print("it goes here")
    #  also tried mode='P'
    while ahk.key_state("XButton2"):
        print("this does not appear")
        ahk.send_input("{WheelUp}", blocking=False)
        time.sleep(0.010)

ahk.add_hotkey("XButton2", callback=scroll_up)
ahk.start_hotkeys()
ahk.block_forever()
```

> I have a [Redragon Mouse which has two side buttons](https://www.redragonzone.com/collections/mice/products/redragon-m991-wireless-gaming-mouse-19000-dpi-wired-wireless-gamer-mouse-w-rapid-fire-key) they're normally mapped to <kbd>Forward</kbd> and <kbd>Backward</kbd> (those are XButton1 and XButton2).  Now to prevent wear and general fatigue of using mouse wheel for scrolling I want to map those two buttons as mouse wheel up and down.  I also use <kbd>Ctrl</kbd>-WheelUp/Down to zoom in and out so I would like to have the same capability, and in addition have a different set of sleep timings when I am doing the zoom.

**Comment by trajano** [comment]
I also tried this
```
    ahk.run_script('''
        While GetKeyState("XButton2", "p") {
            SendEvent "{WheelUp}"
            Sleep 10 
        }
        ''')
```
no luck

**Comment by spyoungtech** [comment]
Hmm. I will try to test this later and see if I can reproduce or confirm a fix, but my first thought would be to try prepending your hotkey with the `~` modifier so the key's native functionality is not blocked by the hotkey hook.

**Comment by spyoungtech** [comment]
Yeah, so, when I test this, I can reproduce your problem.

I was able to fix it by making the change I described above:

```diff
- ahk.add_hotkey("XButton2", callback=scroll_up)
+ ahk.add_hotkey("~XButton2", callback=scroll_up)
```

Let me know if that works for you.

**Comment by trajano** [comment]
It did thanks, do you mind putting that in the documentation somewhere,

**Comment by trajano** [comment]
Now I just need to figure out how to make it NOT trigger the default behaviour because I want to swap it with wheel up

```
def scroll_up():
    while ahk.key_state("XButton2"):
        ahk.send_input("{WheelUp}")
        time.sleep(0.010)

def scroll_down():
    while ahk.key_state("XButton1"):
        ahk.send_input("{WheelDown}")
        time.sleep(0.010)

ahk.add_hotkey("~XButton2", callback=scroll_up)
ahk.add_hotkey("~XButton1", callback=scroll_down)
ahk.start_hotkeys()
ahk.block_forever()
```

These two buttons are the two side buttons of the mouse I am using which defaults to Forward and Backward on the web browser

**Comment by trajano** [comment]
I got it working in the end when I saw the `Up` keyword in the hotkey

```python
from ahk import AHK
import time

ahk = AHK(
    executable_path="C:\\Users\\trajano\\AppData\\Local\\Programs\\AutoHotkey\\v2\\AutoHotkey64.exe",
    version="v2",
)

scrolling_up = False
scrolling_down = False

def scroll_up():
    global scrolling_up
    scrolling_up = True
    while scrolling_up:
        ahk.send_input("{WheelUp}")
        time.sleep(0.010)


def scroll_up_stop():
    global scrolling_up
    scrolling_up = False


def scroll_down_stop():
    global scrolling_down
    scrolling_down = False


def scroll_down():
    global scrolling_down
    scrolling_down = True
    while scrolling_down:
        ahk.send_input("{WheelDown}")
        time.sleep(0.010)

ahk.add_hotkey("XButton2", callback=scroll_up)
ahk.add_hotkey("XButton1", callback=scroll_down)
ahk.add_hotkey("XButton2 Up", callback=scroll_up_stop)
ahk.add_hotkey("XButton1 Up", callback=scroll_down_stop)
ahk.start_hotkeys()
ahk.block_forever()
```

But it seems a bit hacky and I'd rather just use `key_state`

**Comment by trajano** [comment]
In addition when I do

```
def scroll_up():
    global scrolling_up
    scrolling_up = True
    while scrolling_up:
        print(ahk.key_state("LCtrl"))
        # ahk.send_input("{WheelUp}")
        time.sleep(0.010)


ahk.add_hotkey("*XButton2", callback=scroll_up)
ahk.add_hotkey("*XButton2 Up", callback=scroll_up_stop)

```
The process of sending `{WheelUp}` seems to break the key state check.  That may mean there's a concurrency issue with `get_key_state`.

**Comment by spyoungtech** [comment]
> The process of sending {WheelUp} seems to break the key state check. 

@trajano If you mean the key state of a modifier key like `LCtrl`, that is due to an AutoHotkey behavior that affects the key state of modifier keys before sending input. You can address this by using [blind mode](https://www.autohotkey.com/docs/v2/lib/Send.htm#Blind) which disables those behaviors.

```py
        print(ahk.key_state("LCtrl"))
        ahk.send_input("{Blind}{WheelUp}")
```

**Comment by trajano** [comment]
I'll add it to the OP but basically it's this
> I have a [Redragon Mouse which has two side buttons](https://www.redragonzone.com/collections/mice/products/redragon-m991-wireless-gaming-mouse-19000-dpi-wired-wireless-gamer-mouse-w-rapid-fire-key) they're normally mapped to <kbd>Forward</kbd> and <kbd>Backward</kbd> (those are XButton1 and XButton2).  Now to prevent wear and general fatigue of using mouse wheel for scrolling I want to map those two buttons as mouse wheel up and down.  I also use <kbd>Ctrl</kbd>-WheelUp/Down to zoom in and out so I would like to have the same capability, and in addition have a different set of sleep timings when I am doing the zoom.

**Comment by trajano** [comment]
Also
>         print(ahk.key_wait("LCtrl", timeout=0.3)) is not valid as timeout is an integer according to the typings.

**Comment by trajano** [comment]
Given your suggestions though, I ended up with this and seems to work
```
def scroll_up():
    global scrolling_up
    scrolling_up = True
    while scrolling_up:
        ahk.send_input("{Blind}{WheelUp}")
        if ahk.key_state("LCtrl"):
            time.sleep(0.300)
        else:
            time.sleep(0.010)
```

**Comment by spyoungtech** [comment]
Glad you were able to get something that works for you.

> is not valid as timeout is an integer according to the typings.

You're right. The type hint is not quite correct since AutoHotkey will also accept a float. I will fix this in an upcoming release.

**Comment by trajano** [comment]
I'm closing this off, I do have a work around and the more I look at it, the more I think it's a limitation on the architecture working with AHK and nothing can really be done on the python end.
