### ISSUE TITLE
Compile scripts?

### ISSUE THREAD

**Issue by spyoungtech** [spyoungtech/ahk#30]
Wondering if the `ActionChain` implementation (#25) could be changed to support creating a single script that could then be compiled into an exe. Maybe a `compile` method that produces an exe that should, more or less, be the same as using the `.perform` method when executed.

An interface for this might look like
```py
ac = ActionChain()
ac.mouse_drag(size, 0, relative=True)
ac.mouse_drag(0, size, relative=True)
ac.mouse_drag(size * -1, 0, relative=True)
ac.mouse_drag(0, size*-1, relative=True)
ac.compile('draw_square.exe')
```

**Comment by spyoungtech** [comment]
Good callout @SafetyCar -- if this gets an implementation, it should document what benefits compilation does (and does not) offer.

One of my thoughts here are that a script author may want to produce a portable `.exe` so that solutions could be distributed to users without AHK or Python.

**Comment by Nickiel12** [comment]
perhaps add a function to action chain like this
`
action_c = ActionChain()
... 
# Do things here
...
action_c.compile(output_path)
`

**Comment by spyoungtech** [comment]
For design reasons, this feature will not be implemented using the AHK compiler.

Instead, we will focus on supporting compiling Python apps with tools such as PyInstaller.
