### ISSUE TITLE
Add numlock and scroll lock set states

### ISSUE THREAD

**Issue by trajano** [spyoungtech/ahk#307]
### Checked the documentation

- [X] I have checked [the documentation](https://ahk.readthedocs.io/en/latest/api/methods.html) for the feature I am requesting

### describe your feature request

Not sure but why is numlock and scrolllock not implemented?

https://www.autohotkey.com/docs/v2/lib/SetNumScrollCapsLockState.htm

**Comment by spyoungtech** [comment]
Thanks for raising the issue. Just haven't gotten around to it, yet. But since I've got an open request for it, I'll probably implement it soon :-)

I try to document the status of these things in [the methods documentation](https://ahk.readthedocs.io/en/latest/api/methods.html).

**Comment by spyoungtech** [comment]
This is now available in version 1.7.3

Let me know if you have any further questions or issues with this!

**Comment by trajano** [comment]
works well thanks
