### ISSUE TITLE
Wrong Type of keyDelay of send command

### ISSUE THREAD

**Issue by zzsimplezz** [spyoungtech/ahk#315]
### describe your issue

cmd: `ahk.send(keyStr, key_delay=50)`
- In v1: it works fine.
- In v2 it crash with error: `ahk.message.AHKExecutionException: Error occurred in SetKeyDelay (line 1850). The error message was: Parameter #2 of SetKeyDelay requires a Number, but received an empty string..`

Thank you for your lib. :D

### AutoHotkey version

v2

### Code to reproduce the issue

```python
# ahk v2
ahk.send("anything", key_delay=50)
```

**Comment by spyoungtech** [comment]
Thanks. Reproduced and confirmed. I should be able to have a fix out shortly.

**Comment by spyoungtech** [comment]
This should now be fixed in v1.7.5

Keep in mind, AutoHotkey v2 uses `Input` as its default SendMode. As noted in the [SetKeyDelay](https://www.autohotkey.com/docs/v2/lib/SetKeyDelay.htm) documentation, key delay has no effect when the SendMode is `Input`.

So, if you're using AutoHotkey v2, you'll have to change the sendmode to see the effect take place properly:

```py
from ahk import AHK
ahk = AHK(version='v2')

ahk.send('anything', key_delay=50, send_mode='Event')
# OR
ahk.set_send_mode('Event')
ahk.send('anything', key_delay=50)
```


Please try out the latest version and let me know if that fixes the problem or if you have any other issues. Thanks!

**Comment by zzsimplezz** [comment]
It seems like the method `set_send_mode` dont have _type definition_ => it doesn"t show in vscode suggestion. Can you check and fix it??

**Comment by spyoungtech** [comment]
Hmm. @zzsimplezz  The method does have type hints and I can see it properly in my PyCharm editor. I'm not sure why vscode would not show it.

The accepted arguments are the same as [in AutoHotkey's `SendMode`](https://www.autohotkey.com/docs/v1/lib/SendMode.htm). 

The signature looks like this.
```py
SendMode: TypeAlias = Literal['Event', 'Input', 'InputThenPlay', 'Play', '']  # defined in `_types.py`
def set_send_mode(self, mode: SendMode) -> None:
    ...
```
And can be found [here](https://github.com/spyoungtech/ahk/blob/ed959b3d7ae5738cfddbc1db9db288034afa2c8f/ahk/_async/engine.py#L329) for the async version and [here](https://github.com/spyoungtech/ahk/blob/ed959b3d7ae5738cfddbc1db9db288034afa2c8f/ahk/_sync/engine.py#L324) for the sync version.

We use mypy with strict type checking, which does not allow untyped definitions and those checks also pass. My best guess is it may be a problem with vscode.
