### ISSUE TITLE
To send key press or release event to a ahk window?

### ISSUE THREAD

**Issue by vfptr** [spyoungtech/ahk#326]
### Checked the documentation

- [X] I have checked [the documentation](https://ahk.readthedocs.io/en/latest/api/methods.html) for the feature I am requesting

### describe your feature request

I want to simulate long press event by sending keys release or press event to a not activated window. I did not find any way to do this in AHK.Window class.

**Comment by spyoungtech** [comment]
The way you do this is through the `send` method of the `Window` class and works the same way as described in the docs describing [Repeating or Holding Down a Key](https://www.autohotkey.com/docs/v1/lib/Send.htm#Repeating_or_Holding_Down_a_Key). (these features also work with `ControlSend`, which is the underlying functionality of `Window.send`).

For example, the AutoHotkey documentation provides:

```ahk
Send {Up down}  ; Presses down the up-arrow key.
Sleep 1000  ; Keeps it down for one second.
Send {Up up}  ; Releases the up-arrow key.
```

The equivalent doing what you want to a window that is not active:
```py
win = ahk.win_get(title='my window')
win.send('{Up down}')
time.sleep(1)
win.send('{Up up}')
```

**Comment by vfptr** [comment]
Thank you very much for your answer
