### ISSUE TITLE
can't pass {key up} through window send

### ISSUE THREAD

**Issue by Apprisco** [spyoungtech/ahk#336]
### describe your issue

Can't hold keys in the background for windows like ahk controlsend can do.

**Comment by spyoungtech** [comment]
This is possible. Please provide the code you're trying to use that's not working.

**Comment by Apprisco** [comment]
Please give an example, I'm trying to send it to the window directly which only has win.sendKeys, if i pass in {E up} it dies with list out of index.
I've gotten it working with this:
        hold_script=f'''\
        WinGet, id, ID, {self.username}
        ControlSend,, {{Blind}}{{{char} down}}, ahk_id %id%
        '''
        hold_script2=f'''\
        WinGet, id, ID, {self.username}
        ControlSend,, {{Blind}}{{{char} up}}, ahk_id %id%
        '''
        ahk.run_script(hold_script,blocking=False)
        await asyncio.sleep(self.delay*20)
        ahk.run_script(hold_script2,blocking=False)
        await asyncio.sleep(self.delay/5)

**Comment by spyoungtech** [comment]
For games, it can sometimes be challenging. But I believe you have the right approach. Here's an example in my macro software for the game Helldivers2 and how you can accomplish it using `win.send`

https://github.com/spyoungtech/helldivers2-macros/blob/366c3fcaff96ea705d0cb74952cc6ae3d530c543/hd2_macros/macro.py#L84-L86

**Comment by Apprisco** [comment]
Latest from pip, but honestly this method works. I'm good on finding another :)

**Comment by Apprisco** [comment]
@spyoungtech I believe {c DOWN} {c UP} works in win.send, but not {c down} and {c up} like AHK.
That's funny!
