### ISSUE TITLE
Adding a callback to an async function for asyncahk

### ISSUE THREAD

**Issue by Apprisco** [spyoungtech/ahk#343]
### Checked the documentation

- [X] I have checked [the documentation](https://ahk.readthedocs.io/en/latest/api/methods.html) for the feature I am requesting

### describe your feature request

`ahk.add_hotkey('MButton',callback=self.skip())`
I have tried multiple different methods to no avail.
All give an error while the closest i've gotten is below.
```
 Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\envs\Trove\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Andrew\Anaconda3\envs\Trove\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Andrew\Anaconda3\envs\Trove\lib\site-packages\ahk\_hotkey.py", line 299, in dispatcher
    assert hot_thing.callback is not None
AssertionError
```

```
def skip(self):
    asyncio.create_task(hi())
```

If I try to do an async skip function here, it doesn't work at all.

**Comment by spyoungtech** [comment]
Try: `callback=self.skip` (not `self.skip()`)

**Comment by spyoungtech** [comment]
If you still need help, feel free to open another issue. Closing this as stale.
