### ISSUE TITLE
Glyph.ahk.mouse_position value is wrong compared to win32api

### ISSUE THREAD

**Issue by Apprisco** [spyoungtech/ahk#344]
### describe your issue

print(ahk.mouse_position,wa.GetCursorPos()) gives different values on a multi monitor system. This is especially bad as the Window subclass works perfectly, giving the correct position via get_position.

### Code to reproduce the issue

```python
print(ahk.mouse_position,wa.GetCursorPos())
```

**Comment by spyoungtech** [comment]
Did you set the appropriate CoordMode type? https://www.autohotkey.com/docs/v2/lib/CoordMode.htm
