### ISSUE TITLE
Differentiate two keyboards.

### ISSUE THREAD

**Issue by john012343210** [spyoungtech/ahk#345]
### Checked the documentation

- [X] I have checked [the documentation](https://ahk.readthedocs.io/en/latest/api/methods.html) for the feature I am requesting

### describe your feature request

I want to use two keyboards for two different sets of mapping.    Is this library current available to differentiate different keyboards

**Comment by spyoungtech** [comment]
The library uses AutoHotkey, so if AutoHotkey can do this, then the library can probably also do it. If AutoHotkey does not have this functionality, then probably not. 

That said, I'm not aware of any AutoHotkey feature for this. As far as I know, AutoHotkey works "above" the device layer and doesn't expose any low level/hardware events, so I don't think there's a practical approach for this with AutoHotkey itself (or this library, consequently).
