### ISSUE TITLE
Alternative to list_controls()?

### ISSUE THREAD

**Issue by codychen98** [spyoungtech/ahk#347]
### Checked the documentation

- [X] I have checked [the documentation](https://ahk.readthedocs.io/en/latest/api/methods.html) for the feature I am requesting

### describe your feature request

I know list_control() will return all the controls a window has, but it takes lots of time to try each control at a time to see which is the one that I want.

Is it possible to have the option to return the control for the current active control instead of return all the controls for that active window? So if I click on "Setting" button in the outlook app, it will return the control for that specific button that I just clicked on. Thanks!

**Comment by spyoungtech** [comment]
Hmm. I'm not sure how practical it is to create something like a callback in response to clicking a button in another app, but the Window Spy utility is probably the most useful way to get the information you're looking for, which I believe includes information about the active window/control or window/control under the mouse cursor, among other information.

As noted in the [AutoHotkey docs](https://www.autohotkey.com/docs/v2/howto/ManageWindows.htm):

> AutoHotkey comes with a script called Window Spy, which can be used to confirm the title, class and process name of a window. The class and process name are often used when identifying a window by title alone is not feasible. You can find Window Spy in the script's [tray menu](https://www.autohotkey.com/docs/v2/Program.htm#tray-icon) or the [AutoHotkey Dash](https://www.autohotkey.com/docs/v2/Program.htm#dash).

Have you tried using Window Spy?
