### ISSUE TITLE
Again cannot import name 'AHK'

### ISSUE THREAD

**Issue by YesHub** [spyoungtech/ahk#39]
Using python 3.72, CMD can be imported, Vscode editor .py file can't be imported, what's wrong?

**Comment by spyoungtech** [comment]
Hmm. Since it works from CMD, must be a problem with how VS Code is configured. Can you confirm that Vscode is configured to use Python 3.7 and the package is installed?

You can try printing out `sys.version` at the top of your script...

```python
import sys
print(sys.version)
from ahk import AHK
```

**Comment by YesHub** [comment]
Sorry, it's editor problem, if the file in workspace folder can't import , but don't know how to solve it.

**Comment by spyoungtech** [comment]
On the off chance you happen to be naming your file "ahk.py" that would cause a name conflict and cause the error you see. If that's the case, name your file something else.

**Comment by YesHub** [comment]
Exactly! Thank you Very match!
