### ISSUE TITLE
Please add the ToolTip and TrayTip function

### ISSUE THREAD

**Issue by YesHub** [spyoungtech/ahk#40]
The two functions feels good

**Comment by spyoungtech** [comment]
Yep, these are planned to be implemented as part of #11 

Should be available in the next release or two.

**Comment by YesHub** [comment]
thank you! looking forward to the next update :)

**Comment by yedhrab** [comment]
Hello, I implemented these funcs. But there is a trouble on UTF-8 chars like `şığü` and emojies `🦅`

**Comment by spyoungtech** [comment]
Hi @YesHub this change has been merged in #92 and will be included in the next release

**Comment by spyoungtech** [comment]
Released in v0.10.0
