### ISSUE TITLE
Getting script output before closing it. [Not issue, just asking for help]

### ISSUE THREAD

**Issue by btvoidx** [spyoungtech/ahk#43]
How i can run script that returns information to python before exiting?
For example, i run python script that shows nothing in console and starts AHK script with GUI button. Then i press this button and python console shows me "pressed!". Then i press it again and "pressed!" appears second time in python console. Then i close GUI and python script finishes itself.

I did something, but my example does not works.
```python
from ahk import AHK
from ahk.window import Window

gui = """
#SingleInstance, force
#NoTrayIcon
#Persistent

Gui, bfb:Add, Button, x5 y5 w140 h90 gBigButton, DON'T PRESS
Gui, bfb:Show, w150 h100, lmao
Gui, bfb:-MinimizeBox
return

BigButton:
FileAppend, "Button pressed!", *
return

bfbGuiClose:
ExitApp
"""

def main():
	try:
		ahk = AHK(executable_path="AutoHotkey.exe")
	except:
		return

	print("Starting getting information from script!")
	result = ahk.run_script(gui, blocking=False)
	while True:
		print(result.stdout)

if __name__ == '__main__':
	main()
```

**Comment by spyoungtech** [comment]
This is a bit tricky because of how Windows filehandles (including stdin/stdout) work.

There might be an easier solution, but one solution would be to have your script output to a file and poll that file for new contents.

So if you change this line in the `gui` script

```ahk
FileAppend, "Button pressed!", *
```
to
```ahk
FileAppend, "Button pressed!", foo.txt
```
Then the following Python could be used to check if the button has been pressed while the GUI is still running.
```python
result = ahk.run_script(gui, blocking=False)
old_pos = 0
while result.poll() is None: # keep going until subprocess terminates
    with open('foo.txt') as f:
        f.seek(old_pos)
        data = f.read()
        pos = f.tell()
        if old_pos != pos:  # if cursor position changed, data was read
            print('got data:', data)
        else:
            print('No data yet...')
        old_pos = pos
    time.sleep(1)  # polling interval
```

**Comment by spyoungtech** [comment]
Been looking into this one some more. I'm not really sure exactly why this only works with a file and not stdout.

This will be important for when the GUI functionality is introduced into this package.
