### ISSUE TITLE
raise ExecutableNotFoundError('Could not find AutoHotkey.exe on PATH.

### ISSUE THREAD

**Issue by vectinaton** [spyoungtech/ahk#44]
![Capture](https://user-images.githubusercontent.com/50148504/56976958-08376980-6b6c-11e9-9190-5f7af1c77c28.PNG)

**Comment by spyoungtech** [comment]
If you have the autohotkey executable downloaded, but not on PATH, you can use the following code

```python
from ahk import AHK
ahk = AHK(executable_path="C:\\Path\\To\\AutoHotkey.exe")
```

**Comment by vectinaton** [comment]
still not working
![still not working](https://user-images.githubusercontent.com/50148504/57020643-d1bc2600-6c21-11e9-9bb4-4f15572fdcdd.PNG)

**Comment by vectinaton** [comment]
how to know if it is on the path or not?

**Comment by vectinaton** [comment]
![tihs](https://user-images.githubusercontent.com/50148504/57022257-7fc9cf00-6c26-11e9-9052-485809c3cc34.PNG)
![help](https://user-images.githubusercontent.com/50148504/57022276-8ce6be00-6c26-11e9-9572-a32f4d0e81af.PNG)

**Comment by spyoungtech** [comment]
You must locate the actual path of `AutoHotkey.exe` on your system. What I provided is meant to be an example.

**Comment by vectinaton** [comment]
i did this too
![1](https://user-images.githubusercontent.com/50148504/57182855-6336cc80-6e9c-11e9-9e4a-d1d483e807f7.PNG)

**Comment by vectinaton** [comment]
I also switched to python 3.73 32 bit but it still not working

**Comment by spyoungtech** [comment]
You have an extra line calling `ahk = AHK()` again there. It's not needed. The first one with `executable_path=...` worked.

**Comment by lyonferris** [comment]
How can I output Chinese with send ?

**Comment by vectinaton** [comment]
it works thanks a lot !!!!
