### ISSUE TITLE
Case while Set up mouse keys

### ISSUE THREAD

**Issue by spanwair** [spyoungtech/ahk#47]
Hello,
I got little issue when I started using mouse on keypad ala 'Set up Mouse Keys' on windows.
On key Number5 it listen to mouse click, in real world.
In Ahk it send me back numer 5, meaning - type in number instead of pressing Number5 and click down mouse.
Do you know any workaround for this issue?

**Comment by spyoungtech** [comment]
I see. I think this is an expected behavior in AHK. I suppose as a workaround if you want to click the mouse, you can use `ahk.click()` instead. Or use `ahk.mouse_move` in palce of the movement keys.

**Comment by spanwair** [comment]
:) yes I got this idea too, but I would like to continue with mentioned option. Anyway thank you for your contribution

**Comment by spyoungtech** [comment]
I'm going to go ahead and close this. If you have any further questions on this, feel free to comment/re-open.

Thanks!
