### ISSUE TITLE
How to stop ahk script in mid run?

### ISSUE THREAD

**Issue by Nickiel12** [spyoungtech/ahk#50]
I am trying to write a hotkey class version that binds functions to hotkeys. (https://github.com/Nickiel12/ahk/tree/Bindable-Hotkeys)  My question is, is there a way to stop a running script? Or listen for a hotkey and exit after 3 seconds? I am using file write to see if the hotkey had been pressed. My problem is when I try to shut it down, the script doesn't stop till the hotkey is pressed and exitapp is called.

**Comment by Nickiel12** [comment]
and I don't know how to put a label on the question

**Comment by spyoungtech** [comment]
Hmm. Good question. Currently, the only inbuilt mechanism for stopping a running script is the `.stop` method of a hotkey instance, which kills the subprocess running the hotkey using the [terminate](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.terminate) method. 

Additionally, if you use the `run_script` method with `blocking=False` you will receive back a [`Popen` object](https://docs.python.org/3/library/subprocess.html#popen-objects) which you can call the `terminate` method on yourself.

As far as _listening_ for a hotkey, reacting to a hotkey with Python code is something that's not currently provided for (see #9 ) but there might be a few ways to do this. I think you're on the right track with your solution. See [this comment](https://github.com/spyoungtech/ahk/issues/43#issuecomment-489402221) which describes how you might be able to watch for the output of a script and do something with it.


Lastly, you also have the option of controlling the behavior entirely in an AutoHotkey script. For example, the following script will listen for `ctrl+alt+s` then sleep for 3 seconds, then exit.

```python
script = """
^!s::
Sleep, 3000
ExitApp
"""
ahk.run_script(script)
```

**Comment by Nickiel12** [comment]
Hey! I got it working, it is updated on my fork. I will be trying to find a better more efficient way to do it in the days to come, but, Hey it Works!!!
