### ISSUE TITLE
Contribution, how to ask questions about syntax and naming schemes 

### ISSUE THREAD

**Issue by Nickiel12** [spyoungtech/ahk#51]
How should I go about  asking questions about things like syntax, code requirements, what should/shouldn't be added, etc, if I want to contribute. Questions like this one.

 I think I might have found a great solution for ahk->python communication, but it requires win32 to work. Is requiring win32 as a module acceptable?

**Comment by Nickiel12** [comment]
Using win32 you can get events like change in file size, name, etc. Here's my reference (just a tutorial i'm copying **cough** I mean utilizing) [here](http://timgolden.me.uk/python/win32_how_do_i/watch_directory_for_changes.html#use_findfirstchange)

**Comment by spyoungtech** [comment]
Great question. GitHub issues are perfectly fine for asking questions like this. I suppose I ought to get around to writing up a contribution guide of sorts. In the meantime, hopefully this will get you by:

I have no major requirements, but as a general guideline for code style, PEP 8 works for me. If you use the [`black`](https://github.com/python/black) code formatting tool, I like using it with the following parameters

```
black --line-length 120 --skip-string-normalization somemodule.py
```

Regarding ahk->python communication, adding a dependency on win32 sounds reasonable to me. Feel free to open up a PR or discuss on a GH issue and I would be happy to review/discuss when I have the time.

**Comment by Nickiel12** [comment]
PR?

**Comment by spyoungtech** [comment]
PR = pull request :)

**Comment by Nickiel12** [comment]
As for win32, I am thinking of a wrapper class that can be used elsewhere, but I need to spend some time on the idea. Thanks!

**Comment by Nickiel12** [comment]
As for win32, I am thinking of a wrapper class that can be used elsewhere, but I need to spend some time on the idea. Thanks!
