### ISSUE TITLE
communication decoding

### ISSUE THREAD

**Issue by Nickiel12** [spyoungtech/ahk#53]
I am using the win32 to get a windows event when a file changes. I need some help with a design decision. What happens in the below code is as follows
1. initiate class
2. define a win32 event and start a loop to get events
3. when it gets an event.... _aaaand_ here is where I get stuck.

I need help choosing which of the following to use. Do I have one file that all ahk scripts write to with each hotkey writing an identifying code to the file, and check the most recent code to a dict etc. Or do I make a separate file for every hotkey with the hotkey code in the name and trigger the last_edited_event. 

The First Choice
Ups - one file, simpler
downs - complex(er) decoding, long uses of the program with frequent use could lead to large files because if I delete the last hotkey-code, it might accidentally block a hotkey write. (Though, admittedly, this is less of a concern than it could be, depending how python handles opening and reading files)

The Second Choice
Ups - read/writes are simpler, decoding is simpler
downs - finding the changed file could be resource intensive as all files have to be checked

So it comes down to, Large files from extended runs VS large CPU usage when a lot of ahk communication files are present.

PS. Same thing but another system for live data transfer like your "filewrite *"

`
class Abstract_Communicator(metaclass=abc.ABCMeta):

    def __init__(self, directory:str):

        if directory == None:
            self.path = pathlib.Path(os.path.abspath(".")) / "tmp"
        else:
            if type(directory) != str: 
                raise TypeError(f"Expected type str, but got type {type(directory)}")
            
            self.path = pathlib.Path(directory)
        if not self.path.exists():
            raise FileNotFoundError(f"The directory or file at {self.path} doesn't exist")
        
        self.stop_thread = False
        self.thread = threading.Thread(target=self.event_loop)
        self.thread.start()

    def __del__(self):
        self.stop_thread = True  

    @abc.abstractmethod
    def on_event(self):
        print("An event!!!")

    def event_loop(self):
        change_handle = win32file.FindFirstChangeNotification (
        str(self.path),
        0,
        win32con.FILE_NOTIFY_CHANGE_LAST_WRITE
        )

        try:
            while self.stop_thread == False:
                result = win32event.WaitForSingleObject (change_handle, 500)

                #
                # If the WaitFor... returned because of a notification (as
                #  opposed to timing out or some error) then look for the
                #  changes in the directory contents.
                #
                if result == win32con.WAIT_OBJECT_0:
                    self.on_event()
                win32file.FindNextChangeNotification (change_handle)

        finally:
            win32file.FindCloseChangeNotification (change_handle)

class EventListener(Abstract_Communicator):

    
    
    def on_event(self):
        #this isn't totally implemented
        return super().on_event()
`

**Comment by Nickiel12** [comment]
This code isn't even to to point of testing yet, but it gives you an idea of what I am doing.

**Comment by Nickiel12** [comment]
I am now looking into if it would be worth it to make a compiled c++ (that and c# are the only c languages I am familiar with at the moment) module to do this check

**Comment by spyoungtech** [comment]
Interesting. Another thought for communication could be TCP-based sockets. One example in the wild is [this project](https://github.com/irthomasthomas/helpmecode) which uses AutoHotkey and Python together, communicating with sockets.

**Comment by Nickiel12** [comment]
I am not _quite_ that experienced in ahk to pull that off at the moment. But if you would prefer a socketed approach, I will see what I can do.

**Comment by Nickiel12** [comment]
Is it ok that I am planning to add onto the AHK class? I would like the loop to be in a global(-ish) class so that there aren't hundreds of them floating about.
