### ISSUE TITLE
Is there any particular reason there isn't a gitignore?

### ISSUE THREAD

**Issue by Nickiel12** [spyoungtech/ahk#55]
When I am working on the repo, I keep having to bulk commit changed .pyc binary files. Is there a reason that there isn't a .gitignore file to keep this from happening?

**Comment by spyoungtech** [comment]
No particular reason. I normally don't track my .gitignore files with Git, but feel free to contribute one if you feel it would be useful.

**Comment by spyoungtech** [comment]
Resolved by #56
