### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by ed06b008** [spyoungtech/ahk#64]
I used the following code

from ahk import AHK
ahk = AHK(executable_path="C:\\Path\\To\\AutoHotkey.exe")
ahk.mouse_move(x=100, y=100, blocking=True)

I am encountering the following error. I am not sure how to resolve. Can someone help?

![Capture](https://user-images.githubusercontent.com/9678190/69186812-518ade80-0ae7-11ea-8eee-5088ef0d06aa.PNG)

**Comment by Pestitschek** [comment]
Most likely you do not have an AutoHotkey interpreter .exe (or equivalent/variant) in the path C:\Path\To\AutoHotkey.exe
(even more so judging by the fact that the path you have shown "C:\Path\To\AutoHotkey.exe" is the placeholder example in the website)

You are meant to change the argument "executable_path" to a valid interpreter OR add AutoHotkey executable to your system variables PATH and call AHK() without parameters.

**Comment by ed06b008** [comment]
Thanks for the prompt response. It worked. On of the examples indicates on how to open "notepad" using AHK. Could you please let me know whether this package is capable of interacting with the window (saving the file, changing the format of the text etc.) as well? If so, could you share how it needs to be done? Thanks in advance.

**Comment by spyoungtech** [comment]
Glad you were able to figure out your initial issue.

> Could you please let me know whether this package is capable of interacting with the window (saving the file, changing the format of the text etc.) as well? 

This package is capable of running any AutoHotkey script, so, anything AutoHotkey can do could be achieved through this package (at least through `ahk.run_script`). Some features, like [Control](https://www.autohotkey.com/docs/commands/Control.htm) are not _yet_ implemented.

I think as a starting point you can try automating keyboard shortcuts in notepad using the keyboard features of this package. For example, sending `CTRL+S` should save the file. Feel free to open another issue if you have more questions.
