### ISSUE TITLE
Trying to acquire pixel color raises WinError 5

### ISSUE THREAD

**Issue by slobodaapl** [spyoungtech/ahk#69]
Seems to be a permission related issue.
Unsure how to fix this.

Simple code ran from PyCharm:

```
from ahk import AHK

ahk = AHK(executable_path='C:\\Program Files\\AutoHotkey')
a = ahk.pixel_get_color(2, 2)
print(a)
```

**Comment by spyoungtech** [comment]
Ah, this is probably because `executable_path='C:\\Program Files\\AutoHotkey'` is not correct. This should be the _full_ path to the executable, including the `.exe` extension.

**Comment by slobodaapl** [comment]
> Ah, this is probably because `executable_path='C:\\Program Files\\AutoHotkey'` is not correct. This should be the _full_ path to the executable, including the `.exe` extension.

Great. That is probably the issue indeed. Will attempt to add code for dynamic exe detection if the path is wrong.
