### ISSUE TITLE
Missing Directives

### ISSUE THREAD

**Issue by spyoungtech** [spyoungtech/ahk#7]
Currently the directives implementations are incomplete. Particularly, directives which take in parameters are not fully implemented.

I think defaults for arguments should be the same as in AutoHotkey, unless a good argument can be made for a more sensible default. We may also opt to provide defaults where AutoHotkey does not.

Anything that is deprecated, not recommended, or being removed in AutoHotkey v2.0 should not be implemented.

**Comment by spyoungtech** [comment]
I believe, if you know what arguments are expected, you can actually instantiate the incomplete directives.

So, specifically, the goal here is to add `__init__` methods to incomplete directives and provide the proper signature and docstrings.

**Comment by Nickiel12** [comment]
Could you define "directive" in this use case?

**Comment by spyoungtech** [comment]
Directives, as in AutoHotkey script directives. Some examples include `#NoEnv` `#NoTrayIcon` `#Persistent` and many more. The wrapper implements these in [directives.py](https://github.com/spyoungtech/ahk/blob/master/ahk/directives.py) -- For instance, the implementation of [ClipboardTimeout](https://github.com/spyoungtech/ahk/blob/master/ahk/directives.py#L51-L54) maps to the Autohotkey directive [`#ClipboardTimeout`](https://www.autohotkey.com/docs/commands/_ClipboardTimeout.htm)

Some directives are missing, others take arguments that could be defined and documented.

Hope that answers your question @Nickiel12
