### ISSUE TITLE
How to check specific radius of pixels?

### ISSUE THREAD

**Issue by L4ur3nsk1s** [spyoungtech/ahk#79]
In ahk you can search pixel in specific radius of pixels, but in python ahk you can search in only one pixel.

PixelSearch, Px, Py, 679, 380, 687, 388, 0x00008C, 1, Fast
ahk.pixel_search('0x00008C')  
Is there any way to check radius, but not a pixel?

Sorry for bad english, it's not my native language..

**Comment by spyoungtech** [comment]
[pixel_search](https://ahk.readthedocs.io/en/latest/api/screen.html#ahk.screen.ScreenMixin.pixel_search) has two arguments to specify the region to search in; `upper_bound` and `lower_bound`.

```python
top_left = (679, 380)
bottom_right =(687, 388)
ahk.pixel_search('0x00008C', upper_bound=top_left, lower_bound=bottom_right)
```

I'll plan to add better description for the parameters soon :)

**Comment by spyoungtech** [comment]
I'm going to close this for now, but please do let me know if you still have further questions on this.
