### ISSUE TITLE
German umlaute with python 3.7+ not working as expected

### ISSUE THREAD

**Issue by M6D6M6A** [spyoungtech/ahk#86]
Hello,
i try to write a script that writes ingame item names in the chat, but all umlauts are displayed funny (e.g. http://i.gyazo.com/3df9910aff56e821f362e6a88f084acf.png). does anyone know how i can solve this problem?
I use Windows 10 and have the Unicode 64 bit version of AHK v1.1.32.00.

When I execute the following code I get the character Ã¼ in game, but I expect ü
(I Have a German keyboard and layout in Windows!)

`ahk.send_input("ü")`

**Comment by spyoungtech** [comment]
Proper handling for unicode is a known issue right now. 

Perhaps one way to get around this would be to use the escape sequence like `{U+00FC}`.

In the future, I hope to have better handling for these cases. See also #45
