### ISSUE TITLE
ClipWait?

### ISSUE THREAD

**Issue by PeterStavrou** [spyoungtech/ahk#87]
This wrapper is awesome!
Is it possible to somehow do a ClipWait?
ahk.ClipWait(2000) for example?

Reference: 
https://www.autohotkey.com/docs/commands/ClipWait.htm

**Comment by spyoungtech** [comment]
Yeah, I think it makes sense to implement clipwait and other similar functionality for clipboard

**Comment by spyoungtech** [comment]
clip_wait is now implemented and released in v1
